config/routes.rb
Rails.application.routes.draw do
  resources :activities
  get 'contact/index'

  get 'members/index'

  devise_for :admins
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
  		#get "like", to: "posts#upvote"
  		#get "dislike", to: "posts#downvote"
  	end
    resources :comments, :only => [:create]
  end
  
  resources :tangazos
  resources :user_steps
  devise_for :users
  get 'home/index'
  root 'home#index'
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :trackable, polymorphic: true
  attr_accessor :action, :trackable

  cattr_accessor :current_user
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :post
  	belongs_to :user

  	cattr_accessor :current_user
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessor :body

	#validates :body, length: { maximum: 200 }
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_many :votes, dependent: :destroy

	cattr_accessor :current_user

=begin method to vote with acts as votable
	def score
		self.get_upvotes.size 
		self.get_downvotes.size
	end
=end
end

app/models/tangazo.rb
class Tangazo < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x350#", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :large => "350x350>", :medium => "200x200#", :thumb => "40x40>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  		if login = conditions.delete(:login)
    		where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  		else
    		if conditions[:username].nil?
      			where(conditions).first
    		else
      			where(username: conditions[:username]).first
    		end
  		end
	end

  has_many :posts
  has_many :comments
  has_many :activities

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def create
        @post = Post.find(params[:post_id])
        @comment = @post.current_user.comments.create!(params.require(:comment).permit!) 
        @comment.user_id = current_user.id
        @comment.post_id = @post.id

        track_activity @comment
        redirect_to posts_path
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
  	@users = User.all.order('created_at DESC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #@comments = Comment.where(post_id: @post)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        #callback 
        track_activity @post

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        track_activity @post
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json

   
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    track_activity @post
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.votes.create
    redirect_to(posts_path)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes.last.destroy
    redirect_to(posts_path)
  end
=begin voting with gem acts as votable
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to :back
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
	def new
	end

	def create
	end
	
	def show
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tangazos_helper.rb
module TangazosHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
    	<%#= comment.user.username %>
 
        <%#= time_ago_in_words(comment.created_at) %> <!-- not really necessary for comments -->
        <%= comment.user.username %>, <%= comment.body %><br/>
    </p>
<% end %>

app/views/posts/_form.html.erb
<div>  
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div>
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table>
    <thead>
      <tr>
        <th>Body</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.user.username %><br><%= time_ago_in_words(post.created_at) %></td>
          <td><%= link_to (post.body),post %></td>
          <td>
            <h2>Comments</h2>
              <div id="comments">
                <%= pluralize(post.comments.count, "Comment") %><br>

                <!-- please activate font awesome -->
                <%= pluralize(post.votes.count, "like") %>
                <%= link_to 'Like', upvote_post_path(post), class: "fa fa-thumbs-up", method: :post %>
                <%= link_to 'Dislike', downvote_post_path(post), class: "fa fa-thumbs-down", method: :post %>

              </div>
              <%= form_for [post, Comment.new] do |f| %>
                <p>
                  <%#= comment.user.username %>
                  <%= f.label :body, "New comment" %><br/>
                  <%= f.text_area :body %>
                </p>
                <p><%= f.submit "Add comment" %></p>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
 <div> 
  <p id="notice"><%= notice %></p>
  <p><%= @post.user.username %> </p>
  <p>
    <strong>Body:</strong><br>
    <%= @post.body %><br>

    <%#= link_to like_post_path(@post), method: :put, class: "fa fa-thumbs-o-up" %>
    <%#= pluralize(@post.get_upvotes.size, "Like") %><br>
    <%#= link_to dislike_post_path(@post), method: :put, class: "fa fa-thumbs-o-down" %>
    <%#= pluralize(@post.get_downvotes.size, "Dislike") %>
  </p>

  <% if @post.user == current_user %>
  	<%= link_to 'Edit', edit_post_path(@post) %> |
  	<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', posts_path %><br>

  <!-- please activate font awesome -->
  <%= pluralize(@post.votes.count, "like") %> <%= pluralize(@post.comments.count, "Comment") %><br>
  <%= link_to 'Like', upvote_post_path(@post), class: "fa fa-thumbs-up", method: :post %>
  <%= link_to 'Dislike', downvote_post_path(@post), class: "fa fa-thumbs-down", method: :post %>

  <h5>Comments</h5>
  
  <%= form_for [@post, Comment.new] do |f| %>
      <p>
          <%= f.label :body, "Add comment" %><br/>
              <%= f.text_area :body %>
      </p>
      <p><%= f.submit "Add comment" %></p>
  <% end %>
  <div id="comments">
    <%= render :partial => @post.comments %>
  </div>


</div>