config/routes.rb
Rails.application.routes.draw do
  resources :activities
  get 'contact/index'

  get 'members/index'

  devise_for :admins
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
  		#get "like", to: "posts#upvote"
  		#get "dislike", to: "posts#downvote"
  	end
    resources :comments, :only => [:create]
  end
  
  resources :tangazos
  resources :user_steps
  devise_for :users
  get 'home/index'
  root 'home#index'
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :trackable, polymorphic: true
  attr_accessor :action, :trackable

  cattr_accessor :current_user
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :post
  	belongs_to :user

  	cattr_accessor :current_user
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessor :body

	#validates :body, length: { maximum: 200 }
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_many :votes, dependent: :destroy

	cattr_accessor :current_user

=begin method to vote with acts as votable
	def score
		self.get_upvotes.size 
		self.get_downvotes.size
	end
=end
end

app/models/tangazo.rb
class Tangazo < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x350#", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :large => "350x350>", :medium => "200x200#", :thumb => "40x40>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  		if login = conditions.delete(:login)
    		where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  		else
    		if conditions[:username].nil?
      			where(conditions).first
    		else
      			where(username: conditions[:username]).first
    		end
  		end
	end

  has_many :posts
  has_many :comments
  has_many :activities

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :post
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #@comments = Comment.where(post_id: @post)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        #callback 
        track_activity @post

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        track_activity @post
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json

   
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    track_activity @post
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.votes.create
    redirect_to(posts_path)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes.last.destroy
    redirect_to(posts_path)
  end
=begin voting with gem acts as votable
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to :back
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
	def new
	end

	def create
	end
	
	def show
	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tangazos_helper.rb
module TangazosHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectRomance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<header>
	<div class="logo">
		<ul>
			<li><%= image_tag "logo.jpg" %></li>
			<li><span>K</span>enyaRomanceHookup</li>
		</ul>
	</div>
	<!-- Navigation -->
    <nav class="navbar navbar-default ">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a class="navbar-brand page-scroll logo" href="#page-top">
                    <img src="img/sumuni.png">
                </a>-->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav ">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>

                    <li>
                    	<%= link_to 'Home', root_path, class: "page-scroll" %>
                    </li>
                    <li>
                    	<%= link_to 'Members', members_index_path, class: "page-scroll" %>
                    </li>
                    <li>
                    	<%= link_to 'Forum', posts_path, class: "page-scroll" %>
                    </li>
                    <li>
                    	<%= link_to 'Contact', contact_index_path, class: "page-scroll" %>
                    </li>
                    <% if user_signed_in? %>
						<li>
							<%= link_to current_user.username, edit_user_registration_path, class: "page-scroll " %>
						</li>
						<li>
							<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "page-scroll fa fa-sign-out " %>
						</li>
					<% else %>
						<li>
							<%= link_to " Sign in", new_user_session_path, class: "page-scroll fa fa-sign-in" %>
						</li>
						<li>
							<%= link_to " Sign Up", new_user_registration_path, class: "button page-scroll fa fa-user " %>
						</li>
					<% end %>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- change to flassh message and work on the space interference its causing--
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>-->
</header>
	
		



<%= yield %>

<!--
<footer>
        <div>
            <span class="copyright">Copyright &copy; <%= link_to "Jeff","http://www.jeffnyalik.com", target: "_blank" %>
                <script language="JavaScript" type="text/javascript">
                    now = new Date
                    theYear=now.getYear()
                    if (theYear < 1900)
                    theYear=theYear+1900
                    document.write(theYear)
                </script> 
            </span>
        </div>
    </footer>-->
</div><!-- /container -->
</body>
</html>